matrix:
  include:
    - name: "JavaScript"
      language: node_js
      node_js: "node"
      before_install: cd js

    - name: "Java"
      language: java
      before_install: cd java
      script: ./gradlew test

